# Generated by Django 4.1.4 on 2022-12-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the author's first name", max_length=100, verbose_name="Author's first name")),
                ('last_name', models.CharField(help_text="Enter the author's last name", max_length=100, verbose_name="Author's last name")),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter date of birth', null=True, verbose_name='Date of birth')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter the date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=200, verbose_name='Book title')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000, verbose_name='Book abstract')),
                ('isbn', models.CharField(help_text='Must contain 13 characters', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Select the author of the book', null=True, to='catalog.author', verbose_name='Author of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter book genre', max_length=200, verbose_name='Book genre')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language of the book', max_length=200, verbose_name='The language of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the copy status of the book', max_length=20, verbose_name='Book copy status')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Enter the inventory number of the copy', max_length=20, null=True, verbose_name='Inventory number')),
                ('imprint', models.CharField(help_text='Enter the publisher and year of issue', max_length=200, verbose_name='Publisher ')),
                ('due_back', models.DateField(blank=True, help_text='Enter the end of the status period', null=True, verbose_name='Status end date')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change the state of an instance', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Book copy status')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Enter a genre for the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Book genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Select the language of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='The language of the book'),
        ),
    ]
