# Generated by Django 4.1.4 on 2022-12-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Select the author of the book', to='catalog.author', verbose_name='Author of the book'),
        ),
    ]
